services:
  tesloshop-app:
    depends_on:
      - postgres-db
    image: tesloshop-docker
    container_name: teslo-shop
    restart: always
    ports:
      - "${TESLO_SHOP_PORT}:${TESLO_SHOP_PORT}"
    environment:
      PORT: ${TESLO_SHOP_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres-db
    build:
      context: .
      dockerfile: ./apps/teslo-shop/Dockerfile

  postgres-db:
    image: postgres:14.3
    container_name: postgres-tesloshop
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}