services:
  pokedex-app:
    depends_on:
      - mongo-db
    image: pokedex-docker
    container_name: pokedex
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: 5
    build:
      context: .
      dockerfile: ./apps/pokedex/Dockerfile
  
  tesloshop-app:
    depends_on:
      - postgres-db
    image: tesloshop-docker
    container_name: teslo-shop
    restart: always
    ports:
      - "${TESLO_SHOP_PORT}:${TESLO_SHOP_PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${TESLO_SHOP_PORT}
      DEFAULT_LIMIT: 5
    build:
      context: .
      dockerfile: ./apps/pokedex/Dockerfile

  mongo-db:
    image: mongo:5
    container_name: mongo-pokedex
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGODB_DATABASE: ${MONGO_DB}

  postgres-db:
    image: postgres:14.3
    container_name: postgres-tesloshop
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}